Test Tic-Tac-Toe game
collinsugwu/Microverse-203-tic-tac-toe pull request #5
Opened 2019-11-01 21:40 UTC by jairjy

Writing tests for the board.rb class which contains the logic of the Tic-Tac-Toe game

2019-11-02 18:59 UTC, whiz25 commented on spec/board_spec.rb
> +  board = Board.new
use ```let``` for variables. that would now be ```let(:board){Board.new}```

2019-11-02 19:01 UTC, whiz25 commented on spec/board_spec.rb
> +    play1 = Board.new
this violates the DRY principle because it appears three times in your code. turn it into one variable and re-use.
```let(:play1){Board.new}```

2019-11-02 19:01 UTC, whiz25 requested changes
## Good job 👍 
You have correctly implemented tests for the OOP project. That's good. However, the instructions say tests are supposed to be for the OOP and Enumerables projects. You are missing tests for the Enumerable project.
![Screenshot (11)](https://user-images.githubusercontent.com/19773024/68075613-2308c600-fdbb-11e9-9e7f-992397f7a4ae.png)
So;
- [x] add the missing tests
- [x] look at my comments and implement the requested changes

#### Make the requested changes and re-submit for another review.
### Martin Afani

2019-11-05 03:45 UTC, maelfosso requested changes
# Changes required

Hello @collinsugwu @jairjy 

Please, apply the suggested changes requested by the previous reviewers @whiz25 
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-05 03:45 UTC, maelfosso commented on spec/board_spec.rb
> +  validate = Board.new
Please, change that as suggested

2019-11-06 00:37 UTC, stratospherique requested changes
### Great work implementing the suggested changes :clap: We understand that this is the tic tac toe repository and you wrote tests only for it (i.e separated from the Enumerable methods project) :pray: However, some requirements needs to be implemented in order for us to approve your project. check :arrow_down: 

- **[REQUIRED]** Configure your repo so it shows ruby style **checks**. :heavy_check_mark: 

- **[REQUIRED]** Add 'LICENSE' and 'main.bat' to _.gitignore_

### That's it :relaxed: When finished, kindly resubmit another code review request form :pray: 

Happy coding :v: 
**Ahmed Mahfoudh**

2019-11-07 21:07 UTC, maelfosso approved these changes
# Congratulation :smile: You did it :clap: 

You can merge it :+1: 
Good luck with the next project

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-08 14:58 UTC, merged